const ADD_BOOK = 'ADD_BOOK';
const REMOVE_BOOK = 'REMOVE_BOOK';
const EDIT_BOOK = 'EDIT_BOOK';
const UPDATE_PROGRESS = 'UPDATE_PROGRESS';
const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
export {
  ADD_BOOK, REMOVE_BOOK, EDIT_BOOK, UPDATE_PROGRESS, CHANGE_CATEGORY,
};
